packages:
  - packages/*
  - docs
  - packages/playground/**

catalog:
  vite-plugin-dts: ^3.9.1
  vue: ^3.4.31
  vue-router: ^4.4.0
  perfect-debounce: ^1.0.0
  shiki: ^1.10.3
  splitpanes: ^3.1.5
  vue-virtual-scroller: 2.0.0-beta.8
  '@vitejs/plugin-vue': ^5.0.5
  '@iconify/json': ^2.2.225
  '@types/node': ^20.14.10
  '@unocss/reset': ^0.61.3
  floating-vue: 5.2.2
  pinia: ^2.1.7
  sass: ^1.77.6
  unocss: ^0.61.3
  unplugin-auto-import: ^0.17.6
  vite: ^5.3.3
  '@vueuse/core': ^10.11.0
  '@vueuse/integrations': ^10.11.0
  colord: ^2.9.3
  vite-hot-client: ^0.2.3
  mitt: ^3.0.1
  pathe: ^1.1.2
  execa: ^8.0.1
  vite-plugin-inspect: ^0.8.4
  serve: ^14.2.3
  typescript: ^5.5.3
